// Words that can never be used as a custom alias, because they are (or may become)
// real addresses of this service or its website.
export const RESERVED_ALIASES = new Set([
  'about',
  'admin',
  'analytics',
  'api',
  'app',
  'assets',
  'auth',
  'blog',
  'contact',
  'dashboard',
  'docs',
  'favicon',
  'health',
  'help',
  'home',
  'index',
  'keys',
  'link',
  'links',
  'login',
  'logout',
  'me',
  'null',
  'pricing',
  'privacy',
  'register',
  'report',
  'robots',
  'settings',
  'signup',
  'sitemap',
  'static',
  'status',
  'support',
  'terms',
  'undefined',
  'url',
  'urls',
  'usage',
  'user',
  'users',
  'www',
]);

export function isReservedAlias(value) {
  return RESERVED_ALIASES.has(String(value).toLowerCase());
}